params:
  seed: 42

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 2.0
    # can make custom wrapper?
    clip_actions: 0.2

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  # doesn't have this fine grained control but made it close
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: 'logs/rl_games/klask/tuning/nn/klask.pth' # path to the checkpoint to load

  config:
    full_experiment_name: odrive_new_estimator
    name: klask
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: False
    gamma: 0.99
    tau : 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    #score_to_win: 20000
    max_epochs: -1
    max_frames: !!int 10_000_000_000
    save_best_after: 50
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 128 #this is ca 3 s of play time at 50 Hz which should capture most things
    minibatch_size: 128
    mini_epochs: 8 #long horizon puts com overhead on algorithm, therefore you might as well simulate with fresh date more often
    critic_coef: 4
    clip_value: True
    seq_length: 64
    bounds_loss_coef: 0.00000001
    self_play: True
    games_to_track: 100
    self_play_config:
      check_scores: True
      update_score: 0.4
      games_to_check: 1
      #env_update_num: 1

env:
  obs_noise: 0.0
  actuator_model: True
  collision_avoidance: False

rewards:
  time_punishment: !!float 0.00
  shot_over_middle_line: !!float 4.3 #13.33
  player_in_goal: !!float -3.00
  opponent_in_goal: !!float 0.0
  goal_scored: !!float 20.0
  goal_conceded: !!float -15.0
  distance_player_ball_own_half: !!float 0.000
  distance_ball_opponent_goal: !!float 0.0033 #0.0066
  ball_speed: !!float 0.00
  ball_stationary: !!float -0.0025 #-0.002
  collision_player_ball: !!float 0.1 #0.607
  ball_in_own_half: !!float 0.00
  close_to_boundaries: !!float -0.0115 #-0.001
  player_strategically_positioned: !!float 0.092 #0.008

terminations:
  time_out: True
  goal_scored: True
  goal_conceded: True
  player_in_goal: True
  opponent_in_goal: True
