params:
  seed: 3

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 10.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  # doesn't have this fine grained control but made it close
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    full_experiment_name: pretrained_agent_action_1.0_no_add_obs
    name: klask
    env_name: rlgpu
    device: 'cuda:2'
    device_name: 'cuda:2'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.996
    tau : 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.01
    #score_to_win: 20000
    max_epochs: -1
    max_frames: !!int 10_000_000_000
    save_best_after: 50
    save_frequency: 35
    grad_norm: 0.4
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16 #this is ca 3 s of play time at 50 Hz which should capture most things
    minibatch_size: 4096
    mini_epochs: 8 #long horizon puts com overhead on algorithm, therefore you might as well simulate with fresh date more often
    critic_coef: 2.0
    clip_value: True
    seq_length: 16
    bounds_loss_coef: 0.0000001
    self_play: True
    games_to_track: 4096
    self_play_config:
      check_scores: True
      update_score: 0.20
      games_to_check: 1
      env_update_num: 4096

env:
  obs_noise: 0.0
  actuator_model: False
  collision_avoidance: False

rewards:
  time_punishment: -0.0000
  time_out_punishment: 0.0
  shot_over_middle_line: 20.0
  player_in_goal: -3.0
  opponent_in_goal: 0.0
  goal_scored: 5.0
  goal_conceded: -3.0
  distance_player_ball_own_half: 0.0
  distance_ball_opponent_goal: 0.05
  distance_ball_own_goal: -0.05
  ball_speed: 0.0
  ball_stationary: -0.005
  collision_player_ball: 20.0
  ball_in_own_half: 0.0
  close_to_boundaries: -0.01
  player_strategically_positioned: 0.0

terminations:
  time_out: True
  goal_scored: True
  goal_conceded: True
  player_in_goal: True
  opponent_in_goal: True
